import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import logo from "@/src/assets/Logo.png";
import ReduxProvider from "../providers/ReduxProvider";
import Protected from "../components/Protected";
import { Toaster } from "react-hot-toast";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Krishimitra",
  description: "Generated by create-prisma",
  icons: {
    icon: "/favicon.ico", // This looks into the 'public' folder
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body className="flex flex-row h-dvh overflow-hidden">
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
